### ISSUE TITLE
Icon Button Component

### ISSUE THREAD

**Issue by faddalibrahim** [gdscashesi/ashesi-hackers-league#32]
Create a button component which you can pass as props

- [ ] an SVG icon
- [ ] a text
- [ ] a URL

the button when clicked should redirect to the URL prop provided

the icons used here are from [css.gg](css.gg) 

- [ ] download the SVG code of the icons and wrap them as components (like you did for the SVG images of the PageNotFound)

@Simon-157 

![image](https://user-images.githubusercontent.com/41176161/182932944-c87ad559-12a3-4d12-82b2-841490bbc974.png)

**Comment by Simon-157** [comment]
please the css.gg link is not working for me

**Comment by faddalibrahim** [comment]
> please the css.gg link is not working for me

it works

![image](https://user-images.githubusercontent.com/41176161/183151112-3f2cf468-fc13-472e-8a9c-78cd431442b9.png)

**Comment by Simon-157** [comment]
> please the css.gg link is not working for me

sorry it works now

**Comment by Simon-157** [comment]
> > please the css.gg link is not working for me
> 
> it works
> 
> ![image](https://user-images.githubusercontent.com/41176161/183151112-3f2cf468-fc13-472e-8a9c-78cd431442b9.png)

yeah
