### ISSUE TITLE
save questions in local storage

### ISSUE THREAD

**Issue by faddalibrahim** [gdscashesi/ashesi-hackers-league#38]
- [ ] add a save button to the MiniSideNav.js that when clicked, **stringifies** the **questionContent** and stores it in localStorage

currently, any question that is typed in any of the text areas is stored in the **questionContent** state object (logged to the console)

look through the code and understand the mechanics before you attempt this task

if you are not understanding any part, start a call and ping me.

**Comment by Oheneba-Dade** [comment]
Can I just know what exactly you mean by local storage?

**Comment by faddalibrahim** [comment]
look up 

- [ ] **local storage** 
- [ ] **session storage**
- [ ] **cookies**
- [ ] **tokens** 

and learn about them

**Comment by Oheneba-Dade** [comment]
yessir
