### ISSUE TITLE
admin navigation

### ISSUE THREAD

**Issue by faddalibrahim** [gdscashesi/ashesi-hackers-league#39]
- [x] replicate the navigation bar on the admin Figma UI
- [x] the buttons when clicked should lead to the respective routes

the Figma design will be revamped, so just focus on making a simple navbar that routes to the different pages when a particular button is clicked

**Comment by Simon-157** [comment]
> * [ ]  replicate the navigation bar on the admin Figma UI
> * [ ]  the buttons when clicked should lead to the respective routes
> 
> the Figma design will be revamped, so just focus on making a simple navbar that routes to the different pages when a particular button is clicked

Please should this be done in the component folder or in the admin folder

**Comment by faddalibrahim** [comment]
in the admin folder for now.
