### ISSUE TITLE
Setup admin context

### ISSUE THREAD

**Issue by faddalibrahim** [gdscashesi/ashesi-hackers-league#57]
There is already an **AppContext** whose provider is wrapped around the whole **App.js**. This will make sure every data in the context is accessible by every component. 

However, we would also want a separate context for only the admin pages so that admin-specific data is not exposed on the user side.

Here is what to do...

- [x] Create an **AdminContext** and wrap its provider around the **/admin** route
- [ ] if the json server is already setup, simulate fetching data from the server and updating states in the context (let me know if this is clear enough)

**Comment by Simon-157** [comment]
Has the json server been setup yet?
