### ISSUE TITLE
highlight the column the table has been sorted by

### ISSUE THREAD

**Issue by faddalibrahim** [gdscashesi/ashesi-hackers-league#61]
a basic UX rule is to let the user know **where they currently are** , **what's currently happening** or **what has just happened**

on the rankings page,

what happens when a user clicks on the table headers to sort the table? Well, the user would see a quick re-ordering of the table, and that's it. That would be so brief, and the feedback is not quite settling.

**how about we highlight the column to demonstrate that the table has indeed been sorted according to the values of that column? cool, right?**

yeah, not cool until we implement it. Get to work asap!😆

NB: This should be done after the [sort function fix](https://github.com/gdscashesi/ashesi-hackers-league/issues/59) issue has been merged

**Comment by Simon-157** [comment]
is it only the column header cell that needs to be highlighted

**Comment by faddalibrahim** [comment]
> is it only the column header cell that needs to be highlighted

all the cells in that column

**Comment by Simon-157** [comment]
oh okay cool
