### ISSUE TITLE
Update Table with points

### ISSUE THREAD

**Issue by faddalibrahim** [gdscashesi/ashesi-hackers-league#67]
This page will let us update the table with points for the individual teams

page: **/admin/update**

We will re-use the table component, and add an additional column : **action**
This column will contain **3 counter buttons** for each of algo, scripting, SQL for updating a specific row

|rank | name |algorithms |scripting |sql |total|action
|--|--|--|--|--|--|--|
|1|Berekusu Warriors|21|45|3|69| +- +- +-|
|2|Ashesi Ninjas|27|9|6|42| +- +- +- |
|3|Crusading Coders|18|1|0|19| +- +- +-|

but here comes the **hard part**

- [ ] we should be able to look at the before and after states of the table (before updating, after updating because the ranking will change)

but for now, implement just the action column and make sure its working. Let me know when this is done before you start the **hard part**

If you have a better/interesting way we can do this. Let me know ASAP. Otherwise, start work!

**Comment by Simon-157** [comment]
how should the points be update upon clicking on an action button? should it pop up an input field to change the score or pop  up increment and decrement buttons?

**Comment by faddalibrahim** [comment]
> how should the points be update upon clicking on an action button? should it pop up an input field to change the score or pop up increment and decrement buttons?

I don't get this well. could you elaborate further?

**Comment by Simon-157** [comment]
> > how should the points be update upon clicking on an action button? should it pop up an input field to change the score or pop up increment and decrement buttons?
> 
> I don't get this well. could you elaborate further?

Sorry, I just realized that the buttons are supposed to be counters. I get it now

**Comment by faddalibrahim** [comment]
> > > how should the points be update upon clicking on an action button? should it pop up an input field to change the score or pop up increment and decrement buttons?
> > 
> > 
> > I don't get this well. could you elaborate further?
> 
> Sorry, I just realized that the buttons are supposed to be counters. I get it now

alright

**Comment by Simon-157** [comment]
I am having difficulties with persistence of the update data since there is no api to update data scores of the fetched data.
When the action button is clicked, it only gets updated at the admin page . I tried to update the context scores with the setScore state, for testing but it did not work

**Comment by faddalibrahim** [comment]
> I am having difficulties with persistence of the update data since there is no api to update data scores of the fetched data. When the action button is clicked, it only gets updated at the admin page . I tried to update the context scores with the setScore state, for testing but it did not work

alright. lets jump on a call

**Comment by Simon-157** [comment]
> > I am having difficulties with persistence of the update data since there is no api to update data scores of the fetched data. When the action button is clicked, it only gets updated at the admin page . I tried to update the context scores with the setScore state, for testing but it did not work
> 
> alright. lets jump on a call

yeah sure
