### ISSUE TITLE
Error404 for admin routes not accurate

### ISSUE THREAD

**Issue by faddalibrahim** [gdscashesi/ashesi-hackers-league#68]
instead of 

sorry, looks like we don't have a **hello** page

it shows 

sorry looks like we don't have a **admin** page

and it's the same for every other invalid route following **/admin**

![image](https://user-images.githubusercontent.com/41176161/195729378-37fa86de-d3f4-4ca1-8025-65898cf1907b.png)

**Comment by JuniorAt-29** [comment]
yeah, that was a mistake instead of showing the last route with no match I showed the parent route as not found.

**Comment by Simon-157** [comment]
yeah, that was a mistake instead of showing the last route with no match I showed the parent route as not found.

**Comment by faddalibrahim** [comment]
alright
